### PR TITLE
Geekie bugfix

### PR DESCRIPTION
**Pull request by dilidili**
- When using the text tool, not having the text "type something". Often the text does not disappear when you start typing.
- When using the zoom tool, it should have buttons to zoom in and out with maximum zoom at 200% and minimum zoom at 50%. Only the trackpad is not intuitive. Buttons increment/decreases 10%.
- When using the pencil, shape, or text tool, the font size and color options box should be exposed while I have the tool selected.

### CODE REVIEW

**Comment by dilidili** [comment]
Append two fixes in this MR:

- The default value of pencil, shape and text tools should be Normal and not Small value.
- When it has background image, if I use the eraser, it won’t erase the background image, just the layers above.

**Comment by gabrielguilhoto** [comment]
Hi @dilidili, thanks for the PR. GitHub says "This branch cannot be rebased due to conflicts". I can solve this here, but for the next PRs could you please create the new branch from the master branch to avoid conflicts?

**Comment by dilidili** [comment]
Hi @gabrielguilhoto, could you give me more details about the confilict? From my side, there are no conflicts exist. 
image

**Comment by gabrielguilhoto** [comment]
Hi @dilidili, I was using the "rebase and merge option":

Screen Shot 2022-05-12 at 09 36 52
 
But looking at the commits I don't see why there would be conflicts. I guess I can use the other merge options, no need to worry on your side.

**Pull request merged**
